#!/usr/bin/perl

use Getopt::Long;

my $show_line = 3;
my $q;
my $file;

GetOptions("n=i" => \$show_line);

if (@ARGV == 2) {
        $q = $ARGV[0];
        $file = $ARGV[1];
} else {
        die("target keyword and file are needed. \n usage: aroundgrep \"hoge\" fugafuga.txt");
}


open(FILE, "< $file") or die("error :$!");

my $hit = 1;
my @hit_lines;
while (my $line = <FILE>) {
        if ($line =~ /${q}/) {
                for (my $i = $show_line * (-1) ; $i <= $show_line ; $i++) {
                        push(@hit_lines, $. + $i);
                }
        }
        $hit++;
}
close FILE;

@hit_lines = sort {$a <=> $b} @hit_lines;

open(FILE, "< $file") or die("error :$!");
while(my $line = <FILE>) {
        foreach $hit_line (@hit_lines) {
                if ($. == $hit_line) {
                        printf "%s: %s", $., $line;
                }
        }
}
close FILE;
